import type {Scenario,Simulation,Model} from '../types';
const BASE=import.meta.env.VITE_API_URL || 'http://localhost:8000';
const demoModel:Model={nombre:'3-PG + LSTM',metricas:{r2:.92,rmse:13.2,mae:8.7,roc_auc:.95},source_version:'synthetic_test'};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export function demoSimulation(s:Scenario):Simulation{const b=210, n=8.4, r=.28; const biomass=b*(1-s.clareo_pct/100-s.quema_pct/220)+s.restauracion_plantas_ha*.018+s.manejo_combustibles*.04; const risk=clamp(r+s.clareo_pct*.002+s.quema_pct*.0025-s.restauracion_plantas_ha*.00018-s.manejo_combustibles*.004+(55-s.fmc)*.003+(1.8-s.lai)*.04+(1-s.ndvi)*.12, .02,.98); const npp=n*(1+s.lai*.03+s.ndvi*.08+s.precipitacion_mm/10000-s.temperatura_c*.002)+s.restauracion_plantas_ha*.003-s.quema_pct*.015; const temporal=Array.from({length:12},(_,i)=>{const season=Math.sin(i/12*Math.PI*2)*.05;return {period:`2026-${String(i+1).padStart(2,'0')}`,baseline: b*(1+i*.003)+season*20,scenario: biomass*(1+i*.003)+season*18,riesgo_base:clamp(r+season*.4,.03,.7),riesgo_escenario:clamp(risk+season*.4,.03,.98)}}); const trees=Array.from({length:700},(_,i)=>{const x=(i%35)/34*100-50,y=Math.floor(i/35)/19*60-30,h=7+(Math.sin(i*12.3)*.5+.5)*22+(x+y)*.02; const rr=clamp(risk+(Math.sin(i*.77)*.5)*.2,.03,.98);return{x,y,height:clamp(h,5,32),crown:1.2+h*.09,biomass:biomass/210*(h/18),risk:rr,loss:clamp(s.ndvi<.45?Math.random()*.3:Math.random()*.08,0,1),elevation:92,en_subparcela_3d:Math.abs(x)<=100&&Math.abs(y)<=100}});return{source_version:'synthetic_test',baseline:{biomasa:b,npp:n,riesgo:r},scenario:{biomasa:biomass,npp,riesgo:risk},delta:{biomasa:biomass-b,npp:npp-n,riesgo:risk-r},temporal,trees,insumos:{gestion:{clareo_pct:s.clareo_pct,quema_pct:s.quema_pct,restauracion_plantas_ha:s.restauracion_plantas_ha,manejo_combustibles:s.manejo_combustibles},vegetacion_efectiva:{ndvi:s.ndvi,lai:s.lai,fmc:s.fmc,precipitacion_mm:s.precipitacion_mm,temperatura_c:s.temperatura_c},modelos:[{objetivo:'Biomasa',modelo:'DEMO sintÃ©tico',tipo:'FÃ³rmula analÃ­tica (sin modelo)',predictoras:[{nombre:'Clareo',valor:s.clareo_pct,unidad:'%'},{nombre:'Quema',valor:s.quema_pct,unidad:'%'},{nombre:'RestauraciÃ³n',valor:s.restauracion_plantas_ha,unidad:'pl/ha'},{nombre:'NDVI',valor:s.ndvi,unidad:''}],resultado:biomass,unidad:'Mg/ha'},{objetivo:'Riesgo incendio',modelo:'DEMO sintÃ©tico',tipo:'FÃ³rmula analÃ­tica (sin modelo)',predictoras:[{nombre:'FMC',valor:s.fmc,unidad:'%'},{nombre:'LAI',valor:s.lai,unidad:'mÂ²/mÂ²'},{nombre:'NDVI',valor:s.ndvi,unidad:''}],resultado:risk,unidad:'probabilidad'},{objetivo:'NPP',modelo:'DEMO sintÃ©tico',tipo:'FÃ³rmula analÃ­tica (sin modelo)',predictoras:[{nombre:'LAI',valor:s.lai,unidad:'mÂ²/mÂ²'},{nombre:'NDVI',valor:s.ndvi,unidad:''}],resultado:npp,unidad:'Mg C/ha/aÃ±o'}],interpretaciones:['Modo offline: FastAPI no disponible, el resultado se calculÃ³ con la fÃ³rmula sintÃ©tica en el navegador.','Conecta el backend (uvicorn) para usar los modelos entrenados reales (AGB_GEDI, INCENDIO, 3PG_LSTM).']}}}
export async function getModel():Promise<Model>{try{const r=await fetch(`${BASE}/modelo/mejor`);if(!r.ok)throw Error();return r.json()}catch{return demoModel}}
export async function simulate(s:Scenario):Promise<Simulation>{try{const r=await fetch(`${BASE}/simular`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)});if(!r.ok)throw Error();return r.json()}catch{return demoSimulation(s)}}
export async function getDictionary(){try{const r=await fetch(`${BASE}/diccionario`);if(!r.ok)throw Error();return r.json()}catch{return {fmc:{unit:'%',min:20,max:100},lai:{unit:'mÂ²/mÂ²',min:.5,max:8},ndvi:{unit:'',min:0,max:1}}}}
export async function explicarEstado():Promise<{configurado:boolean}>{try{const r=await fetch(`${BASE}/explicar/estado`);if(!r.ok)throw Error();return await r.json()}catch{return{configurado:true}}}
export async function explicarIA(escenario:Scenario,simulation:Simulation):Promise<string>{const r=await fetch(`${BASE}/explicar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({escenario,simulation})});if(!r.ok){let det='Error al contactar Gemini';try{det=(await r.json()).detail||det}catch{}throw new Error(det)}const d=await r.json();return d.explicacion}
